### ISSUE TITLE
Formal verification wishlist

### ISSUE THREAD

**Issue by MathisGD** [morpho-org/bundler3#126]
- [x] Adapters functions calls either revert or change the state, see #229 .
- [x] Properties about "exactly one zero" for morpho inputs, see #195 .
- [x] Verify that adapters that are not supposed to reenter the bundler can't do it, see #209 .
- [x] The transient storage is null after a call to `multicall`, see #178 and #200 .
- [x] Verify the approvals are reset to zero in untrusted contracts, see #217 and #238 .
